//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:9.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SkiaSharp;

namespace CraftSynth.ImageEditor.Properties {
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager? resourceMan;
        
        private static global::System.Globalization.CultureInfo? resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CraftSynth.ImageEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo? Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type SKBitmap.
        /// </summary>
        internal static SKBitmap? RelationshipsHS {
            get {
                object? obj = ResourceManager.GetObject("RelationshipsHS", resourceCulture);
                if (obj == null) return null;
                
                // Convert from System.Drawing.Bitmap to SKBitmap if needed
                if (obj is System.Drawing.Bitmap systemBitmap)
                {
                    return ConvertSystemBitmapToSKBitmap(systemBitmap);
                }
                
                // If already SKBitmap (shouldn't happen with current resource system)
                if (obj is SKBitmap skBitmap)
                {
                    return skBitmap;
                }
                
                // If it's byte array, decode directly
                if (obj is byte[] bytes)
                {
                    return SKBitmap.Decode(bytes);
                }
                
                return null;
            }
        }
        
        /// <summary>
        /// Helper method to convert System.Drawing.Bitmap to SKBitmap
        /// </summary>
        private static SKBitmap? ConvertSystemBitmapToSKBitmap(System.Drawing.Bitmap systemBitmap)
        {
            if (systemBitmap == null) return null;
            
            try
            {
                // Convert System.Drawing.Bitmap to byte array (PNG format)
                using (var memoryStream = new System.IO.MemoryStream())
                {
                    systemBitmap.Save(memoryStream, System.Drawing.Imaging.ImageFormat.Png);
                    byte[] imageBytes = memoryStream.ToArray();
                    
                    // Create SKBitmap from byte array
                    return SKBitmap.Decode(imageBytes);
                }
            }
            catch (System.Exception)
            {
                // If conversion fails, return null
                return null;
            }
        }
    }
}