//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:8.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using System.Configuration;
using System.Runtime.CompilerServices;
using System.CodeDom.Compiler;

namespace CraftSynth.ImageEditor.Properties
{
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase
    {
        
        private static Settings? defaultInstance = (Settings?)ApplicationSettingsBase.Synchronized(new Settings());
        
        public static Settings Default
        {
            get
            {
                return defaultInstance!;
            }
        }
    }
}