<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <RootNamespace>CraftSynth.ImageEditor.Gui</RootNamespace>
    <AssemblyName>CraftSynth.ImageEditor.Gui</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CraftSynth.ImageEditor\CraftSynth.ImageEditor.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="**/*.resx" />
  </ItemGroup>

</Project>